export const AUDIENCE_THEMES = {
  heritage: {
    id: 'heritage',
    ambientGlow: 'bg-teal-600',
    title: '民俗信仰・文化傳承',
    subtitle: 'Cinematic Pink 賽博霓虹粉',
    desc: '冷冽科技感、高對比度的深邃紫與霓虹粉。專為科技產品、未來趨勢與歷史解密設計。',
    gradient: 'from-[#10B981] to-[#0A2E5C]',
    primaryColor: 'purple-500',
    borderActive: 'border-[#0A2E5C]/50',
    textActive: 'text-[#0A2E5C]',
    bgActive: 'bg-[#10B981]/10',
    bgBadge: 'bg-[#D4AF37]/10 border-[#D4AF37]/20 text-[#D4AF37]',
    primaryBtn: 'bg-gradient-to-r from-[#10B981] to-[#0A2E5C] hover:opacity-90 text-white rounded-full shadow-lg hover:-translate-y-[2px] transition-all duration-300',
    secondaryBtn: 'bg-[#F8FAFC] text-[#1E293B] border-slate-200 hover:bg-slate-100 rounded-full',
    textMuted: 'text-[#64748B]',
    accentText: 'text-[#D4AF37]',
    accentBg: 'bg-[#D4AF37]/10',
    ringColor: 'focus:ring-[#0A2E5C] focus:border-[#0A2E5C]',
    pipelineCurrent: 'bg-white border-[#0A2E5C]/50 shadow-[0_4px_20px_rgba(10,46,92,0.05)]',
    pipelineCurrentIcon: 'bg-[#10B981] text-white animate-pulse',
    tagBg: 'bg-[#F8FAFC] border-slate-200 text-[#64748B]',
    matrixRequired: 'bg-purple-900/50 text-[#10B981] border border-purple-500/30 cursor-not-allowed opacity-80',
    matrixSelected: 'bg-purple-500 text-white shadow-md hover:bg-purple-600',
    matrixUnselected: 'bg-white border border-slate-200 text-[#64748B] hover:bg-purple-50',
    focusRing: 'focus:border-purple-500/50',
    actionBtn: 'bg-purple-600 hover:bg-purple-500 text-white',
    actionBtnOutline: 'bg-purple-500/10 text-purple-600 hover:text-purple-700 border border-purple-500/20 hover:border-purple-500/50 hover:bg-purple-500/20',
    themeLogMessage: '[Theme] 已切換至「民俗信仰・文化傳承 (Cinematic Pink)」模式。優化低光源剪輯視覺，啟動 RGB 電競靈感調幅機制 🟢'
  },
  beauty: {
    id: 'beauty',
    ambientGlow: 'bg-rose-400',
    title: '美妝保養・悅己美學',
    subtitle: 'Glamour Rose 奢華玫瑰金',
    desc: '高質感、溫柔優雅、奢華玫瑰粉與香檳金。專為美妝、穿搭與高感性生活視覺設計。',
    gradient: 'from-[#10B981] to-[#0A2E5C]',
    primaryColor: 'pink-500',
    borderActive: 'border-[#0A2E5C]/50',
    textActive: 'text-[#0A2E5C]',
    bgActive: 'bg-[#10B981]/10',
    bgBadge: 'bg-[#D4AF37]/10 border-[#D4AF37]/20 text-[#D4AF37]',
    primaryBtn: 'bg-gradient-to-r from-[#10B981] to-[#0A2E5C] hover:opacity-90 text-white rounded-full shadow-lg hover:-translate-y-[2px] transition-all duration-300',
    secondaryBtn: 'bg-[#F8FAFC] text-[#1E293B] border-slate-200 hover:bg-slate-100 rounded-full',
    textMuted: 'text-[#64748B]',
    accentText: 'text-[#D4AF37]',
    accentBg: 'bg-[#D4AF37]/10',
    ringColor: 'focus:ring-[#0A2E5C] focus:border-[#0A2E5C]',
    pipelineCurrent: 'bg-white border-[#0A2E5C]/50 shadow-[0_4px_20px_rgba(10,46,92,0.05)]',
    pipelineCurrentIcon: 'bg-[#10B981] text-white animate-pulse',
    tagBg: 'bg-[#F8FAFC] border-slate-200 text-[#64748B]',
    matrixRequired: 'bg-pink-900/50 text-[#10B981] border border-pink-500/30 cursor-not-allowed opacity-80',
    matrixSelected: 'bg-pink-500 text-white shadow-md hover:bg-pink-600',
    matrixUnselected: 'bg-white border border-slate-200 text-[#64748B] hover:bg-pink-50',
    focusRing: 'focus:border-pink-500/50',
    actionBtn: 'bg-pink-600 hover:bg-pink-500 text-white',
    actionBtnOutline: 'bg-pink-500/10 text-pink-600 hover:text-pink-700 border border-pink-500/20 hover:border-pink-500/50 hover:bg-pink-500/20',
    themeLogMessage: '[Theme] 已切換至「美妝保養・悅己美學 (Glamour Rose)」模式。啟動精緻暖色調高光補償，提升美感氛圍 🟢'
  },
  travelpreneur: {
    id: 'travelpreneur',
    ambientGlow: 'bg-amber-500',
    title: '旅遊生活・世界漫遊',
    subtitle: 'Indie Amber 極速金澄風',
    desc: '極速執行力、黃金極簡微光。專為單兵作業、產品發布與高商業價值轉換設計。',
    gradient: 'from-[#10B981] to-[#0A2E5C]',
    primaryColor: 'amber-500',
    borderActive: 'border-[#0A2E5C]/50',
    textActive: 'text-[#0A2E5C]',
    bgActive: 'bg-[#10B981]/10',
    bgBadge: 'bg-[#D4AF37]/10 border-[#D4AF37]/20 text-[#D4AF37]',
    primaryBtn: 'bg-gradient-to-r from-[#10B981] to-[#0A2E5C] hover:opacity-90 text-white rounded-full shadow-lg hover:-translate-y-[2px] transition-all duration-300',
    secondaryBtn: 'bg-[#F8FAFC] text-[#1E293B] border-slate-200 hover:bg-slate-100 rounded-full',
    textMuted: 'text-[#64748B]',
    accentText: 'text-[#D4AF37]',
    accentBg: 'bg-[#D4AF37]/10',
    ringColor: 'focus:ring-[#0A2E5C] focus:border-[#0A2E5C]',
    pipelineCurrent: 'bg-white border-[#0A2E5C]/50 shadow-[0_4px_20px_rgba(10,46,92,0.05)]',
    pipelineCurrentIcon: 'bg-[#10B981] text-white animate-pulse',
    tagBg: 'bg-[#F8FAFC] border-slate-200 text-[#64748B]',
    matrixRequired: 'bg-amber-900/50 text-[#10B981] border border-amber-500/30 cursor-not-allowed opacity-80',
    matrixSelected: 'bg-amber-500 text-white shadow-md hover:bg-amber-600',
    matrixUnselected: 'bg-white border border-slate-200 text-[#64748B] hover:bg-amber-50',
    focusRing: 'focus:border-amber-500/50',
    actionBtn: 'bg-amber-600 hover:bg-amber-500 text-white',
    actionBtnOutline: 'bg-amber-500/10 text-amber-600 hover:text-amber-700 border border-amber-500/20 hover:border-amber-500/50 hover:bg-amber-500/20',
    themeLogMessage: '[Theme] 已切換至「旅遊生活・世界漫遊 (Indie Amber)」模式。高對比金黃預警，啟動單兵作戰、快速發布極速模式 🟢'
  },
  food: {
    id: 'food',
    ambientGlow: 'bg-yellow-400',
    title: '美食料理・風味探索',
    subtitle: 'Golden Saffron 晨曦藏紅花',
    desc: '溫暖、勾引食慾的漸層橘與焦糖色。專為餐飲品牌、食譜教學與美食探店視覺設計。',
    gradient: 'from-[#10B981] to-[#0A2E5C]',
    primaryColor: 'orange-500',
    borderActive: 'border-[#0A2E5C]/50',
    textActive: 'text-[#0A2E5C]',
    bgActive: 'bg-[#10B981]/10',
    bgBadge: 'bg-[#D4AF37]/10 border-[#D4AF37]/20 text-[#D4AF37]',
    primaryBtn: 'bg-gradient-to-r from-[#10B981] to-[#0A2E5C] hover:opacity-90 text-white rounded-full shadow-lg hover:-translate-y-[2px] transition-all duration-300',
    secondaryBtn: 'bg-[#F8FAFC] text-[#1E293B] border-slate-200 hover:bg-slate-100 rounded-full',
    textMuted: 'text-[#64748B]',
    accentText: 'text-[#D4AF37]',
    accentBg: 'bg-[#D4AF37]/10',
    ringColor: 'focus:ring-[#0A2E5C] focus:border-[#0A2E5C]',
    pipelineCurrent: 'bg-white border-[#0A2E5C]/50 shadow-[0_4px_20px_rgba(10,46,92,0.05)]',
    pipelineCurrentIcon: 'bg-[#10B981] text-white animate-pulse',
    tagBg: 'bg-[#F8FAFC] border-slate-200 text-[#64748B]',
    matrixRequired: 'bg-orange-900/50 text-[#10B981] border border-orange-500/30 cursor-not-allowed opacity-80',
    matrixSelected: 'bg-orange-500 text-white shadow-md hover:bg-orange-600',
    matrixUnselected: 'bg-white border border-slate-200 text-[#64748B] hover:bg-orange-50',
    focusRing: 'focus:border-orange-500/50',
    actionBtn: 'bg-orange-600 hover:bg-orange-500 text-white',
    actionBtnOutline: 'bg-orange-500/10 text-orange-600 hover:text-orange-700 border border-orange-500/20 hover:border-orange-500/50 hover:bg-orange-500/20',
    themeLogMessage: '[Theme] 已切換至「美食料理・風味探索 (Golden Saffron)」模式。啟動高飽和誘人濾鏡與溫馨氛圍光 🟢'
  },
  historyMeme: {
    id: 'historyMeme',
    title: '歷史迷因・歲時傳承',
    subtitle: 'Meme Gold 迷因流金',
    desc: '用現代迷因與幽默視角，盤點歷史人物的極限操作與趣事。專為短影音爆款設計。',
    gradient: 'from-[#10B981] to-[#0A2E5C]',
    primaryColor: 'amber-500',
    borderActive: 'border-[#0A2E5C]/50',
    textActive: 'text-[#0A2E5C]',
    bgActive: 'bg-[#10B981]/10',
    bgBadge: 'bg-[#D4AF37]/10 border-[#D4AF37]/20 text-[#D4AF37]',
    primaryBtn: 'bg-gradient-to-r from-[#10B981] to-[#0A2E5C] hover:opacity-90 text-white rounded-full shadow-lg hover:-translate-y-[2px] transition-all duration-300',
    secondaryBtn: 'bg-[#F8FAFC] text-[#1E293B] border-slate-200 hover:bg-slate-100 rounded-full',
    textMuted: 'text-[#64748B]',
    accentText: 'text-[#D4AF37]',
    accentBg: 'bg-[#D4AF37]/10',
    ringColor: 'focus:ring-[#0A2E5C] focus:border-[#0A2E5C]',
    pipelineCurrent: 'bg-white border-[#0A2E5C]/50 shadow-[0_4px_20px_rgba(10,46,92,0.05)]',
    pipelineCurrentIcon: 'bg-[#10B981] text-white animate-pulse',
    tagBg: 'bg-[#F8FAFC] border-slate-200 text-[#64748B]',
    matrixRequired: 'bg-red-900/50 text-[#10B981] border border-red-500/30 cursor-not-allowed opacity-80',
    matrixSelected: 'bg-red-500 text-white shadow-md hover:bg-red-600',
    matrixUnselected: 'bg-white border border-slate-200 text-[#64748B] hover:bg-red-50',
    focusRing: 'focus:border-red-500/50',
    actionBtn: 'bg-red-600 hover:bg-red-500 text-white',
    actionBtnOutline: 'bg-red-500/10 text-red-600 hover:text-red-700 border border-red-500/20 hover:border-red-500/50 hover:bg-red-500/20',
    themeLogMessage: '[Theme] 已切換至「歷史迷因 (Meme Gold)」模式。啟動迷因引擎，垃圾話滿載準備中 🟢'
  },
  pet: {
    id: 'pet',
    ambientGlow: 'bg-sky-400',
    title: '寵物照護・幸福陪伴',
    subtitle: 'Nurturing Sky 溫和知性藍',
    desc: '傳遞信任與安定的天空藍。專為寵物醫療、動物行為與溫和友善的排版設計。',
    gradient: 'from-[#10B981] to-[#0A2E5C]',
    primaryColor: 'blue-500',
    borderActive: 'border-[#0A2E5C]/50',
    textActive: 'text-[#0A2E5C]',
    bgActive: 'bg-[#10B981]/10',
    bgBadge: 'bg-[#D4AF37]/10 border-[#D4AF37]/20 text-[#D4AF37]',
    primaryBtn: 'bg-gradient-to-r from-[#10B981] to-[#0A2E5C] hover:opacity-90 text-white rounded-full shadow-lg hover:-translate-y-[2px] transition-all duration-300',
    secondaryBtn: 'bg-[#F8FAFC] text-[#1E293B] border-slate-200 hover:bg-slate-100 rounded-full',
    textMuted: 'text-[#64748B]',
    accentText: 'text-[#D4AF37]',
    accentBg: 'bg-[#D4AF37]/10',
    ringColor: 'focus:ring-[#0A2E5C] focus:border-[#0A2E5C]',
    pipelineCurrent: 'bg-white border-[#0A2E5C]/50 shadow-[0_4px_20px_rgba(10,46,92,0.05)]',
    pipelineCurrentIcon: 'bg-[#10B981] text-white animate-pulse',
    tagBg: 'bg-[#F8FAFC] border-slate-200 text-[#64748B]',
    matrixRequired: 'bg-sky-900/50 text-[#10B981] border border-sky-500/30 cursor-not-allowed opacity-80',
    matrixSelected: 'bg-sky-500 text-white shadow-md hover:bg-sky-600',
    matrixUnselected: 'bg-white border border-slate-200 text-[#64748B] hover:bg-sky-50',
    focusRing: 'focus:border-sky-500/50',
    actionBtn: 'bg-sky-600 hover:bg-sky-500 text-white',
    actionBtnOutline: 'bg-sky-500/10 text-sky-600 hover:text-sky-700 border border-sky-500/20 hover:border-sky-500/50 hover:bg-sky-500/20',
    themeLogMessage: '[Theme] 已切換至「寵物照護・幸福陪伴 (Nurturing Sky)」模式。降低視覺刺激，啟動安定、知性與信任感佈局 🟢'
  },
    story: {
    id: 'story',
    ambientGlow: 'bg-indigo-600',
    title: '文化轉譯・銘印說書',
    subtitle: 'Epic Indigo 史詩靛藍',
    desc: '深邃、充滿神秘色彩與故事張力的靛藍色。專為神話傳說、歷史故事與文化解密設計。',
    gradient: 'from-[#4F46E5] to-[#1E1B4B]',
    primaryColor: 'indigo-500',
    borderActive: 'border-[#4F46E5]/50',
    textActive: 'text-[#4F46E5]',
    bgActive: 'bg-[#4F46E5]/10',
    bgBadge: 'bg-[#D4AF37]/10 border-[#D4AF37]/20 text-[#D4AF37]',
    primaryBtn: 'bg-gradient-to-r from-[#4F46E5] to-[#1E1B4B] hover:opacity-90 text-white rounded-full shadow-lg hover:-translate-y-[2px] transition-all duration-300',
    secondaryBtn: 'bg-[#F8FAFC] text-[#1E293B] border-slate-200 hover:bg-slate-100 rounded-full',
    textMuted: 'text-[#64748B]',
    accentText: 'text-[#D4AF37]',
    accentBg: 'bg-[#D4AF37]/10',
    ringColor: 'focus:ring-[#4F46E5] focus:border-[#4F46E5]',
    pipelineCurrent: 'bg-white border-[#4F46E5]/50 shadow-[0_4px_20px_rgba(79,70,229,0.05)]',
    pipelineCurrentIcon: 'bg-[#4F46E5] text-white animate-pulse',
    tagBg: 'bg-[#F8FAFC] border-slate-200 text-[#64748B]',
    matrixRequired: 'bg-indigo-900/50 text-[#818CF8] border border-indigo-500/30 cursor-not-allowed opacity-80',
    matrixSelected: 'bg-indigo-600 text-white shadow-md hover:bg-indigo-700',
    matrixUnselected: 'bg-white border border-slate-200 text-[#64748B] hover:bg-indigo-50',
    focusRing: 'focus:border-indigo-500/50',
    actionBtn: 'bg-indigo-600 hover:bg-indigo-500 text-white',
    actionBtnOutline: 'bg-indigo-500/10 text-indigo-600 hover:text-indigo-700 border border-indigo-500/20 hover:border-indigo-500/50 hover:bg-indigo-500/20',
    themeLogMessage: '[Theme] 已切換至「文化轉譯・銘印說書 (Epic Indigo)」模式。啟動史詩敘事引擎，深邃文化色彩加載中 🟢'
  },
  fintech: {
    id: 'fintech',
    ambientGlow: 'bg-blue-600',
    title: 'FinTech 財經知識・AI 解析',
    subtitle: 'Bloomberg Blue 彭博終端藍',
    desc: '專業客觀、科技感的深藍與金色高光。專為全球總經、金融市場與量化分析視覺設計。',
    gradient: 'from-[#1E3A8A] to-[#0D9488]',
    primaryColor: 'blue-500',
    borderActive: 'border-[#1E3A8A]/50',
    textActive: 'text-[#1E3A8A]',
    bgActive: 'bg-[#1E3A8A]/10',
    bgBadge: 'bg-[#D4AF37]/10 border-[#D4AF37]/20 text-[#D4AF37]',
    primaryBtn: 'bg-gradient-to-r from-[#1E3A8A] to-[#0D9488] hover:opacity-90 text-white rounded-full shadow-lg hover:-translate-y-[2px] transition-all duration-300',
    secondaryBtn: 'bg-[#F8FAFC] text-[#1E293B] border-slate-200 hover:bg-slate-100 rounded-full',
    textMuted: 'text-[#64748B]',
    accentText: 'text-[#D4AF37]',
    accentBg: 'bg-[#D4AF37]/10',
    ringColor: 'focus:ring-[#1E3A8A] focus:border-[#1E3A8A]',
    pipelineCurrent: 'bg-white border-[#1E3A8A]/50 shadow-[0_4px_20px_rgba(30,58,138,0.05)]',
    pipelineCurrentIcon: 'bg-[#1E3A8A] text-white animate-pulse',
    tagBg: 'bg-[#F8FAFC] border-slate-200 text-[#64748B]',
    matrixRequired: 'bg-blue-900/50 text-[#38BDF8] border border-blue-500/30 cursor-not-allowed opacity-80',
    matrixSelected: 'bg-blue-600 text-white shadow-md hover:bg-blue-700',
    matrixUnselected: 'bg-white border border-slate-200 text-[#64748B] hover:bg-blue-50',
    focusRing: 'focus:border-blue-500/50',
    actionBtn: 'bg-blue-600 hover:bg-blue-500 text-white',
    actionBtnOutline: 'bg-blue-500/10 text-blue-600 hover:text-blue-700 border border-blue-500/20 hover:border-blue-500/50 hover:bg-blue-500/20',
    themeLogMessage: '[Theme] 已切換至「FinTech 財經知識 (Bloomberg Blue)」模式。啟動量化金融圖表渲染，調適金藍彭博終端視覺 🟢'
  }
};

export const THEME_STEPS = {
  heritage: [
    { id: 1, name: '核心企劃知識', icon: 'Database', category: 'Research', desc: '針對主題進行定義釐清與客觀史料彙整', type: "text", dependsOn: ["theme"] },
    { id: 2, name: '主軸腳本文案', icon: 'FileText', category: 'Content', desc: "根據基礎背景，產出 5-10 分鐘的 YouTube 長影片文案。", type: "text", dependsOn: ["theme", "step1"] },
    { id: 3, name: '影音 SEO 標題優化', icon: 'Search', category: 'Optimization', desc: "生成標題、標籤與說明欄內容。", type: "text", dependsOn: ["theme", "step2"] },
    { id: 4, name: '擴散式影音文案', icon: 'Video', category: 'Content', desc: "產出 60 秒內的精簡爆款短影片文案。", type: "text", dependsOn: ["theme", "step1"] },
    { id: 5, name: '擴散式 SEO 標籤優化', icon: 'Search', category: 'Optimization', desc: "生成短影片標題與標籤。", type: "text", dependsOn: ["theme", "step4"] },
    { id: 6, name: '影音點擊率 (CTR) 圖像', icon: 'ImageIcon', category: 'Visuals', desc: "生成 3 組 16:9 YouTube 縮圖文案與 AI 繪圖指令。", type: "code", language: "markdown", dependsOn: ["theme", "step3"], aspectRatio: "16:9" },
    { id: 7, name: '擴散式影音吸睛圖像', icon: 'ImageIcon', category: 'Visuals', desc: "生成 3 組 9:16 短影音縮圖文案與 AI 繪圖指令。", type: "code", language: "markdown", dependsOn: ["theme", "step5"], aspectRatio: "9:16" },
    { id: 8, name: '風格化情境視覺', icon: 'ImageIcon', category: 'Visuals', desc: "生成 3 組 16:9 意象圖指令與搭配詩詞。", type: "code", language: "markdown", dependsOn: ["theme"], aspectRatio: "16:9" },
    { id: 9, name: 'Suno AI 情緒配樂', icon: 'Music', category: 'Audio', desc: "生成 3 組符合主題氛圍的音樂生成指令。", type: "code", language: "markdown", dependsOn: ["theme", "step1"] },
    { id: 10, name: '全平台社群推播文案', icon: 'Facebook', category: 'Distribution', desc: "一鍵生成動態視覺提示詞、圖卡排版字卡與社群正文", type: "social", language: "markdown", dependsOn: ["theme", "step1"] }
  ],
  historyMeme: [
    { id: 1, name: '歷史人物硬核迷因大盤點', icon: 'Database', category: 'Research', desc: '用現代迷因與幽默視角，盤點歷史人物的極限操作與趣事', type: "text", dependsOn: ["theme"] },
    { id: 2, name: "短影音腳本撰寫", icon: 'Video', category: 'Content', desc: "產出 60 秒內的精簡爆款短影片文案。", type: "text", dependsOn: ["theme", "step1"] },
    { id: 3, name: "短影音 SEO 優化", icon: 'Search', category: 'Optimization', desc: "生成短影片標題與標籤。", type: "text", dependsOn: ["theme", "step2"] },
    { id: 4, name: "短影音縮圖設計", icon: 'ImageIcon', category: 'Visuals', desc: "生成 3 組 9:16 短影音縮圖文案與 AI 繪圖指令。", type: "code", language: "markdown", dependsOn: ["theme", "step3"], aspectRatio: "9:16" },
    { id: 5, name: "Suno AI 配樂設計", icon: 'Music', category: 'Audio', desc: "生成 3 組符合主題氛圍的音樂生成指令。", type: "code", language: "markdown", dependsOn: ["theme", "step1"] }
  ],
  beauty: [
    { id: 1, name: '核心企劃知識', icon: 'Database', category: 'Research', desc: '針對保養成分或美妝趨勢進行定義釐清與科學/歷史文獻彙整', type: "text", dependsOn: ["theme"] },
    { id: 2, name: '主軸腳本文案', icon: 'FileText', category: 'Content', desc: '根據基礎背景，產出 5-10 分鐘的 YouTube 長影片文案。', type: "text", dependsOn: ["theme", "step1"] },
    { id: 3, name: '影音 SEO 標題優化', icon: 'Search', category: 'Optimization', desc: '生成標題、標籤與說明欄內容。', type: "text", dependsOn: ["theme", "step2"] },
    { id: 4, name: '擴散式影音文案', icon: 'Video', category: 'Content', desc: '產出 60 秒內的精簡爆款短影片文案。', type: "text", dependsOn: ["theme", "step1"] },
    { id: 5, name: '擴散式 SEO 標籤優化', icon: 'Search', category: 'Optimization', desc: '生成短影片標題與標籤。', type: "text", dependsOn: ["theme", "step4"] },
    { id: 6, name: '影音點擊率 (CTR) 圖像', icon: 'ImageIcon', category: 'Visuals', desc: '生成 3 組 16:9 YouTube 縮圖文案與 AI 繪圖指令。', type: "code", language: "markdown", dependsOn: ["theme", "step3"], aspectRatio: "16:9" },
    { id: 7, name: '擴散式影音吸睛圖像', icon: 'ImageIcon', category: 'Visuals', desc: '生成 3 組 9:16 短影音縮圖文案與 AI 繪圖指令。', type: "code", language: "markdown", dependsOn: ["theme", "step5"], aspectRatio: "9:16" },
    { id: 8, name: '風格化情境視覺', icon: 'ImageIcon', category: 'Visuals', desc: '生成 3 組 9:16 高奢行銷海報。', type: "code", language: "markdown", dependsOn: ["theme"], aspectRatio: "9:16" },
    { id: 9, name: 'Suno AI 情緒配樂', icon: 'Music', category: 'Audio', desc: '生成 3 組符合主題氛圍的音樂生成指令。', type: "code", language: "markdown", dependsOn: ["theme", "step1"] },
    { id: 10, name: '全平台社群推播文案', icon: 'Facebook', category: 'Distribution', desc: '一鍵生成動態視覺提示詞、圖卡排版字卡與社群正文', type: "social", language: "markdown", dependsOn: ["theme", "step1"] }
  ],
    food: [
    { id: 1, name: '核心企劃知識', icon: 'Database', category: 'Research', desc: '針對料理、食材、美食文化或飲食趨勢進行科學、歷史與文化查核。', type: "text", dependsOn: ["theme"] },
    { id: 2, name: '主軸腳本文案', icon: 'FileText', category: 'Content', desc: '根據美食背景資料產出5-10分鐘YouTube影片腳本。', type: "text", dependsOn: ["theme", "step1"] },
    { id: 3, name: '影音 SEO 標題優化', icon: 'Search', category: 'Optimization', desc: '生成SEO標題、Hashtags、說明欄。', type: "text", dependsOn: ["theme", "step2"] },
    { id: 4, name: '擴散式影音文案', icon: 'Video', category: 'Content', desc: '生成60秒內爆款短影音腳本。', type: "text", dependsOn: ["theme", "step1"] },
    { id: 5, name: '擴散式 SEO 標籤優化', icon: 'Search', category: 'Optimization', desc: '生成短影音SEO標題。', type: "text", dependsOn: ["theme", "step4"] },
    { id: 6, name: '影音點擊率 (CTR) 圖像', icon: 'ImageIcon', category: 'Visuals', desc: '生成16:9 YouTube縮圖。', type: "code", language: "markdown", dependsOn: ["theme", "step3"], aspectRatio: "16:9" },
    { id: 7, name: '擴散式影音吸睛圖像', icon: 'ImageIcon', category: 'Visuals', desc: '生成9:16 Shorts封面。', type: "code", language: "markdown", dependsOn: ["theme", "step5"], aspectRatio: "9:16" },
    { id: 8, name: '風格化情境視覺', icon: 'ImageIcon', category: 'Visuals', desc: '生成高質感餐飲行銷海報。', type: "code", language: "markdown", dependsOn: ["theme"], aspectRatio: "9:16" },
    { id: 9, name: 'Suno AI 情緒配樂', icon: 'Music', category: 'Audio', desc: '生成三組美食影片音樂。', type: "code", language: "markdown", dependsOn: ["theme", "step1"] },
    { id: 10, name: '全平台社群推播文案', icon: 'Facebook', category: 'Distribution', desc: '生成Instagram、Facebook、小紅書貼文。', type: "social", language: "markdown", dependsOn: ["theme", "step1"] }
  ],
  travelpreneur: [
    { id: 1, name: '核心企劃知識', icon: 'Database', category: 'Research', desc: '蒐集目的地歷史、文化、景點、美食、交通與旅遊資訊，建立可信基礎資料。', type: "text", dependsOn: ["theme"] },
    { id: 2, name: '主軸腳本文案', icon: 'FileText', category: 'Content', desc: '產出8~12分鐘YouTube旅遊攻略影片。', type: "text", dependsOn: ["theme", "step1"] },
    { id: 3, name: '影音 SEO 標題優化', icon: 'Search', category: 'Optimization', desc: '產生YouTube SEO內容。', type: "text", dependsOn: ["theme", "step2"] },
    { id: 4, name: '擴散式影音文案', icon: 'Video', category: 'Content', desc: '生成60秒旅遊Shorts腳本。', type: "text", dependsOn: ["theme", "step1"] },
    { id: 5, name: '擴散式 SEO 標籤優化', icon: 'Search', category: 'Optimization', desc: '生成Shorts SEO。', type: "text", dependsOn: ["theme", "step4"] },
    { id: 6, name: '影音點擊率 (CTR) 圖像', icon: 'ImageIcon', category: 'Visuals', desc: '生成16:9縮圖Prompt。', type: "code", language: "markdown", dependsOn: ["theme", "step3"], aspectRatio: "16:9" },
    { id: 7, name: '擴散式影音吸睛圖像', icon: 'ImageIcon', category: 'Visuals', desc: '生成9:16 Shorts封面。', type: "code", language: "markdown", dependsOn: ["theme", "step5"], aspectRatio: "9:16" },
    { id: 8, name: '風格化情境視覺', icon: 'ImageIcon', category: 'Visuals', desc: '生成高質感旅遊宣傳海報。', type: "code", language: "markdown", dependsOn: ["theme"], aspectRatio: "9:16" },
    { id: 9, name: 'Suno AI 情緒配樂', icon: 'Music', category: 'Audio', desc: '生成旅遊影片背景音樂。', type: "code", language: "markdown", dependsOn: ["theme", "step1"] },
    { id: 10, name: '全平台社群推播文案', icon: 'Facebook', category: 'Distribution', desc: '生成IG、Facebook、Threads、小紅書旅遊貼文。', type: "social", language: "markdown", dependsOn: ["theme", "step1"] }
  ],
  pet: [
    { id: 1, name: '核心企劃知識', icon: 'Database', category: 'Research', desc: '深入分析寵物問題成因、行為學、獸醫觀點與最新研究，建立可信基礎資料。', type: "text", dependsOn: ["theme"] },
    { id: 2, name: '主軸腳本文案', icon: 'FileText', category: 'Content', desc: '產出8~12分鐘問題解決型YouTube影片。', type: "text", dependsOn: ["theme", "step1"] },
    { id: 3, name: '影音 SEO 標題優化', icon: 'Search', category: 'Optimization', desc: '產生YouTube SEO。', type: "text", dependsOn: ["theme", "step2"] },
    { id: 4, name: '擴散式影音文案', icon: 'Video', category: 'Content', desc: '生成60秒爆款短影音。', type: "text", dependsOn: ["theme", "step1"] },
    { id: 5, name: '擴散式 SEO 標籤優化', icon: 'Search', category: 'Optimization', desc: '生成Shorts SEO。', type: "text", dependsOn: ["theme", "step4"] },
    { id: 6, name: '影音點擊率 (CTR) 圖像', icon: 'ImageIcon', category: 'Visuals', desc: '生成三組高CTR縮圖。', type: "code", language: "markdown", dependsOn: ["theme", "step3"], aspectRatio: "16:9" },
    { id: 7, name: '擴散式影音吸睛圖像', icon: 'ImageIcon', category: 'Visuals', desc: '生成9:16封面。', type: "code", language: "markdown", dependsOn: ["theme", "step5"], aspectRatio: "9:16" },
    { id: 8, name: '風格化情境視覺', icon: 'FileText', category: 'Content', desc: '生成高質感寵物宣傳海報、請設計三組寵物品牌海報。', type: "text", dependsOn: ["theme", "step1"] },
    { id: 9, name: 'Suno AI 情緒配樂', icon: 'Music', category: 'Audio', desc: '生成三組寵物影片背景音樂。', type: "code", language: "markdown", dependsOn: ["theme"] },
    { id: 10, name: '全平台社群推播文案', icon: 'Facebook', category: 'Distribution', desc: '生成IG、FB、Threads、小紅書完整貼文。', type: "social", language: "markdown", dependsOn: ["theme", "step1"] }
  ],
    story: [
    { id: 1, name: '核心企劃知識', icon: 'Database', category: 'Research', desc: '基於知名著作，撰寫 1500 字具備起承轉合的沉浸式故事', type: 'text', dependsOn: ['theme'] },
    { id: 2, name: '主軸腳本文案', icon: 'FileText', category: 'Content', desc: '根據故事文本，產出 8 分鐘的 YouTube 沉浸式說書腳本', type: 'text', dependsOn: ['theme', 'step1'] },
    { id: 3, name: '影音 SEO 標題優化', icon: 'Search', category: 'Optimization', desc: '生成吸引故事愛好者與信仰群眾的標題與說明', type: 'text', dependsOn: ['theme', 'step2'] },
    { id: 4, name: '擴散式短影音文案', icon: 'Video', category: 'Content', desc: '產出 180 秒內的極快節奏爆款短片腳本', type: 'text', dependsOn: ['theme', 'step1'] },
    { id: 5, name: '擴散式 SEO 標籤優化', icon: 'Search', category: 'Optimization', desc: '生成短影片封面的衝擊力文案與標籤', type: 'text', dependsOn: ['theme', 'step4'] },
    { id: 6, name: '影音點擊率 (CTR) 圖像', icon: 'ImageIcon', category: 'Visuals', desc: '生成 16:9 YouTube 縮圖文案與 AI 繪圖指令', type: 'code', language: 'markdown', dependsOn: ['theme', 'step3'], aspectRatio: '16:9' },
    { id: 7, name: '擴散式影音吸睛圖像', icon: 'ImageIcon', category: 'Visuals', desc: '生成 9:16 短影音縮圖文案與 AI 繪圖指令', type: 'code', language: 'markdown', dependsOn: ['theme', 'step5'], aspectRatio: '9:16' },
    { id: 8, name: '風格化情境視覺', icon: 'ImageIcon', category: 'Visuals', desc: '生成 16:9 意象圖指令與搭配詩詞', type: 'code', language: 'markdown', dependsOn: ['theme'], aspectRatio: '16:9' },
    { id: 9, name: 'Suno AI 情緒配樂', icon: 'Music', category: 'Audio', desc: '生成 3 組符合主題氛圍的音樂生成指令。', type: 'code', language: 'markdown', dependsOn: ['theme', 'step1'] },
    { id: 10, name: '全平台社群推播文案', icon: 'Facebook', category: 'Distribution', desc: '一鍵生成動態視覺提示詞、圖卡排版字卡與社群正文', type: 'social', language: 'markdown', dependsOn: ['theme', 'step1'] }
  ],
  fintech: [
    { id: 1, name: '核心企劃知識', icon: 'Database', category: 'Research', desc: '針對財經主題進行定義釐清、歷史數據比對與市場影響評估', type: "text", dependsOn: ["theme"] },
    { id: 2, name: '主軸腳本文案', icon: 'FileText', category: 'Content', desc: '根據總經背景，產出 8 分鐘的長影片文案與程式化輸出。', type: "text", dependsOn: ["theme", "step1"] },
    { id: 3, name: '影音 SEO 標題優化', icon: 'Search', category: 'Optimization', desc: '生成高點擊財經標題、標籤與說明欄內容。', type: "text", dependsOn: ["theme", "step2"] },
    { id: 4, name: '擴散式影音文案', icon: 'Video', category: 'Content', desc: '產出 60 秒內的精簡財經爆款短影片文案。', type: "text", dependsOn: ["theme", "step1"] },
    { id: 5, name: '擴散式 SEO 標籤優化', icon: 'Search', category: 'Optimization', desc: '生成短影片標題與標籤。', type: "text", dependsOn: ["theme", "step4"] },
    { id: 6, name: '影音點擊率 (CTR) 圖像', icon: 'ImageIcon', category: 'Visuals', desc: '生成 16:9 YouTube 縮圖文案與 FinTech 風格繪圖指令。', type: "code", language: "markdown", dependsOn: ["theme", "step3"], aspectRatio: "16:9" },
    { id: 7, name: '擴散式影音吸睛圖像', icon: 'ImageIcon', category: 'Visuals', desc: '生成 9:16 短影音縮圖文案與 FinTech 風格繪圖指令。', type: "code", language: "markdown", dependsOn: ["theme", "step5"], aspectRatio: "9:16" },
    { id: 8, name: '風格化情境視覺', icon: 'ImageIcon', category: 'Visuals', desc: '生成 16:9 財經意象行銷海報。', type: "code", language: "markdown", dependsOn: ["theme"], aspectRatio: "16:9" },
    { id: 9, name: 'Suno AI 情緒配樂', icon: 'Music', category: 'Audio', desc: '生成符合市場氛圍的音樂指令。', type: "code", language: "markdown", dependsOn: ["theme", "step1"] },
    { id: 10, name: '全平台社群推播文案', icon: 'Facebook', category: 'Distribution', desc: '一鍵生成數據圖卡提示詞與財經社群正文', type: "social", language: "markdown", dependsOn: ["theme", "step1"] }
  ]
};
