export const AUDIENCE_THEMES = {
  CultureTech: {
    id: 'CultureTech',
    title: '科技文化・未來探索',
    subtitle: 'Cinematic Pink 賽博霓虹粉',
    desc: '冷冽科技感、高對比度的深邃紫與霓虹粉。專為科技產品、未來趨勢與歷史解密設計。',
    gradient: 'from-purple-500 via-pink-500 to-rose-500',
    primaryColor: 'purple-500',
    borderActive: 'border-purple-500/50',
    textActive: 'text-purple-300',
    bgActive: 'bg-purple-600/10',
    bgBadge: 'bg-purple-500/10 border-purple-500/20 text-purple-300',
    primaryBtn: 'bg-gradient-to-r from-purple-600 to-pink-600 hover:from-purple-500 hover:to-pink-500 text-white shadow-purple-500/20',
    secondaryBtn: 'bg-purple-500/10 text-purple-300 border-purple-500/20 hover:bg-purple-500/20',
    textMuted: 'text-purple-400',
    accentText: 'text-pink-400',
    accentBg: 'bg-pink-500/10',
    ringColor: 'focus:ring-purple-500 focus:border-purple-500',
    pipelineCurrent: 'bg-purple-900/40 border-purple-500/50 shadow-[0_0_30px_rgba(168,85,247,0.25)]',
    pipelineCurrentIcon: 'bg-purple-500 text-white animate-pulse',
    tagBg: 'bg-purple-500/10 border-purple-500/20 text-purple-300',
    themeLogMessage: '[Theme] 已切換至「科技文化・未來探索 (Cinematic Pink)」模式。優化低光源剪輯視覺，啟動 RGB 電競靈感調幅機制 🟢'
  },
  beauty: {
    id: 'beauty',
    title: '美妝保養・悅己美學',
    subtitle: 'Glamour Rose 奢華玫瑰金',
    desc: '高質感、溫柔優雅、奢華玫瑰粉與香檳金。專為美妝、穿搭與高感性生活視覺設計。',
    gradient: 'from-rose-400 via-pink-500 to-amber-500',
    primaryColor: 'pink-500',
    borderActive: 'border-pink-500/50',
    textActive: 'text-pink-300',
    bgActive: 'bg-pink-600/10',
    bgBadge: 'bg-pink-500/10 border-pink-500/20 text-pink-300',
    primaryBtn: 'bg-gradient-to-r from-rose-500 to-pink-600 hover:from-rose-400 hover:to-pink-500 text-white shadow-pink-500/20',
    secondaryBtn: 'bg-pink-500/10 text-pink-300 border-pink-500/20 hover:bg-pink-500/20',
    textMuted: 'text-pink-400',
    accentText: 'text-rose-400',
    accentBg: 'bg-rose-500/10',
    ringColor: 'focus:ring-pink-500 focus:border-pink-500',
    pipelineCurrent: 'bg-pink-900/40 border-pink-500/50 shadow-[0_0_30px_rgba(236,72,153,0.25)]',
    pipelineCurrentIcon: 'bg-pink-500 text-white animate-pulse',
    tagBg: 'bg-pink-500/10 border-pink-500/20 text-pink-300',
    themeLogMessage: '[Theme] 已切換至「美妝保養・悅己美學 (Glamour Rose)」模式。啟動精緻暖色調高光補償，提升美感氛圍 🟢'
  },
  travelpreneur: {
    id: 'travelpreneur',
    title: '旅遊生活・世界漫遊',
    subtitle: 'Indie Amber 極速金澄風',
    desc: '極速執行力、黃金極簡微光。專為單兵作業、產品發布與高商業價值轉換設計。',
    gradient: 'from-amber-500 via-orange-500 to-yellow-500',
    primaryColor: 'amber-500',
    borderActive: 'border-amber-500/50',
    textActive: 'text-amber-300',
    bgActive: 'bg-amber-600/10',
    bgBadge: 'bg-amber-500/10 border-amber-500/20 text-amber-300',
    primaryBtn: 'bg-gradient-to-r from-amber-600 to-orange-600 hover:from-amber-500 hover:to-orange-500 text-white shadow-amber-500/20',
    secondaryBtn: 'bg-amber-500/10 text-amber-300 border-amber-500/20 hover:bg-amber-500/20',
    textMuted: 'text-amber-400',
    accentText: 'text-yellow-400',
    accentBg: 'bg-yellow-500/10',
    ringColor: 'focus:ring-amber-500 focus:border-amber-500',
    pipelineCurrent: 'bg-amber-900/40 border-amber-500/50 shadow-[0_0_30px_rgba(245,158,11,0.25)]',
    pipelineCurrentIcon: 'bg-amber-500 text-white animate-pulse',
    tagBg: 'bg-amber-500/10 border-amber-500/20 text-amber-300',
    themeLogMessage: '[Theme] 已切換至「旅遊生活・世界漫遊 (Indie Amber)」模式。高對比金黃預警，啟動單兵作戰、快速發布極速模式 🟢'
  },
  food: {
    id: 'food',
    title: '美食料理・風味探索',
    subtitle: 'Gourmet Ruby 煙火赤紅風',
    desc: '挑逗食慾的寶石紅與珊瑚橘。專為料理探店、食譜分享與高誘惑力視覺設計。',
    gradient: 'from-rose-500 via-red-500 to-orange-500',
    primaryColor: 'red-500',
    borderActive: 'border-red-500/50',
    textActive: 'text-red-300',
    bgActive: 'bg-red-600/10',
    bgBadge: 'bg-red-500/10 border-red-500/20 text-red-300',
    primaryBtn: 'bg-gradient-to-r from-rose-600 to-red-600 hover:from-rose-500 hover:to-red-500 text-white shadow-red-500/20',
    secondaryBtn: 'bg-red-500/10 text-red-300 border-red-500/20 hover:bg-red-500/20',
    textMuted: 'text-red-400',
    accentText: 'text-rose-400',
    accentBg: 'bg-rose-500/10',
    ringColor: 'focus:ring-red-500 focus:border-red-500',
    pipelineCurrent: 'bg-red-900/40 border-red-500/50 shadow-[0_0_30px_rgba(239,68,68,0.25)]',
    pipelineCurrentIcon: 'bg-red-500 text-white animate-pulse',
    tagBg: 'bg-red-500/10 border-red-500/20 text-red-300',
    themeLogMessage: '[Theme] 已切換至「美食料理・風味探索 (Gourmet Ruby)」模式。強化暖色系渲染，啟動高食慾誘惑力調色配置 🟢'
  },
  pet: {
    id: 'pet',
    title: '寵物照護・幸福陪伴',
    subtitle: 'Nurturing Sky 溫和知性藍',
    desc: '傳遞信任與安定的天空藍。專為寵物醫療、動物行為與溫和友善的排版設計。',
    gradient: 'from-sky-500 via-blue-500 to-indigo-500',
    primaryColor: 'blue-500',
    borderActive: 'border-blue-500/50',
    textActive: 'text-blue-300',
    bgActive: 'bg-blue-600/10',
    bgBadge: 'bg-blue-500/10 border-blue-500/20 text-blue-300',
    primaryBtn: 'bg-gradient-to-r from-sky-600 to-blue-600 hover:from-sky-500 hover:to-blue-500 text-white shadow-blue-500/20',
    secondaryBtn: 'bg-blue-500/10 text-blue-300 border-blue-500/20 hover:bg-blue-500/20',
    textMuted: 'text-blue-400',
    accentText: 'text-sky-400',
    accentBg: 'bg-sky-500/10',
    ringColor: 'focus:ring-blue-500 focus:border-blue-500',
    pipelineCurrent: 'bg-blue-900/40 border-blue-500/50 shadow-[0_0_30px_rgba(59,130,246,0.25)]',
    pipelineCurrentIcon: 'bg-blue-500 text-white animate-pulse',
    tagBg: 'bg-blue-500/10 border-blue-500/20 text-blue-300',
    themeLogMessage: '[Theme] 已切換至「寵物照護・幸福陪伴 (Nurturing Sky)」模式。降低視覺刺激，啟動安定、知性與信任感佈局 🟢'
  }
};

export const THEME_STEPS = {
  CultureTech: [
    { id: 1, name: '基礎背景事實查核', icon: 'Database', category: 'Research', desc: '針對主題進行定義釐清與客觀史料彙整', type: "text", dependsOn: ["theme"] },
    { id: 2, name: "長影音腳本撰寫", icon: 'FileText', category: 'Content', desc: "根據基礎背景，產出 5-10 分鐘的 YouTube 長影片文案。", type: "text", dependsOn: ["theme", "step1"] },
    { id: 3, name: "長影音 SEO 優化", icon: 'Search', category: 'Optimization', desc: "生成標題、標籤與說明欄內容。", type: "text", dependsOn: ["theme", "step2"] },
    { id: 4, name: "短影音腳本撰寫", icon: 'Video', category: 'Content', desc: "產出 60 秒內的精簡爆款短影片文案。", type: "text", dependsOn: ["theme", "step1"] },
    { id: 5, name: "短影音 SEO 優化", icon: 'Search', category: 'Optimization', desc: "生成短影片標題與標籤。", type: "text", dependsOn: ["theme", "step4"] },
    { id: 6, name: "長影音縮圖設計", icon: 'ImageIcon', category: 'Visuals', desc: "生成 3 組 16:9 YouTube 縮圖文案與 AI 繪圖指令。", type: "code", language: "markdown", dependsOn: ["theme", "step3"], aspectRatio: "16:9" },
    { id: 7, name: "短影音縮圖設計", icon: 'ImageIcon', category: 'Visuals', desc: "生成 3 組 9:16 短影音縮圖文案與 AI 繪圖指令。", type: "code", language: "markdown", dependsOn: ["theme", "step5"], aspectRatio: "9:16" },
    { id: 8, name: "彩墨風格意象圖", icon: 'ImageIcon', category: 'Visuals', desc: "生成 3 組 16:9 意象圖指令與搭配詩詞。", type: "code", language: "markdown", dependsOn: ["theme"], aspectRatio: "16:9" },
    { id: 9, name: "Suno AI 配樂設計", icon: 'Music', category: 'Audio', desc: "生成 3 組符合主題氛圍的音樂生成指令。", type: "code", language: "markdown", dependsOn: ["theme", "step1"] },
    { id: 10, name: "社群推播發控中心", icon: 'Facebook', category: 'Distribution', desc: "一鍵生成動態視覺提示詞、圖卡排版字卡與社群正文", type: "social", language: "markdown", dependsOn: ["theme", "step1"] }
  ],
  beauty: [
    { id: 1, name: '基礎背景科學查核', icon: 'Database', category: 'Research', desc: '針對保養成分或美妝趨勢進行定義釐清與科學/歷史文獻彙整', type: "text", dependsOn: ["theme"] },
    { id: 2, name: '長影音腳本撰寫', icon: 'FileText', category: 'Content', desc: '根據基礎背景，產出 5-10 分鐘的 YouTube 長影片文案。', type: "text", dependsOn: ["theme", "step1"] },
    { id: 3, name: '長影音 SEO 優化', icon: 'Search', category: 'Optimization', desc: '生成標題、標籤與說明欄內容。', type: "text", dependsOn: ["theme", "step2"] },
    { id: 4, name: '短影音腳本撰寫', icon: 'Video', category: 'Content', desc: '產出 60 秒內的精簡爆款短影片文案。', type: "text", dependsOn: ["theme", "step1"] },
    { id: 5, name: '短影音 SEO 優化', icon: 'Search', category: 'Optimization', desc: '生成短影片標題與標籤。', type: "text", dependsOn: ["theme", "step4"] },
    { id: 6, name: '長影音縮圖設計', icon: 'ImageIcon', category: 'Visuals', desc: '生成 3 組 16:9 YouTube 縮圖文案與 AI 繪圖指令。', type: "code", language: "markdown", dependsOn: ["theme", "step3"], aspectRatio: "16:9" },
    { id: 7, name: '短影音縮圖設計', icon: 'ImageIcon', category: 'Visuals', desc: '生成 3 組 9:16 短影音縮圖文案與 AI 繪圖指令。', type: "code", language: "markdown", dependsOn: ["theme", "step5"], aspectRatio: "9:16" },
    { id: 8, name: '品牌高奢行銷海報', icon: 'ImageIcon', category: 'Visuals', desc: '生成 3 組 9:16 高奢行銷海報。', type: "code", language: "markdown", dependsOn: ["theme"], aspectRatio: "9:16" },
    { id: 9, name: 'Suno AI 配樂設計', icon: 'Music', category: 'Audio', desc: '生成 3 組符合主題氛圍的音樂生成指令。', type: "code", language: "markdown", dependsOn: ["theme", "step1"] },
    { id: 10, name: '社群推播發控中心', icon: 'Facebook', category: 'Distribution', desc: '一鍵生成動態視覺提示詞、圖卡排版字卡與社群正文', type: "social", language: "markdown", dependsOn: ["theme", "step1"] }
  ],
    food: [
    { id: 1, name: '美食基礎知識與文化查核', icon: 'Database', category: 'Research', desc: '針對料理、食材、美食文化或飲食趨勢進行科學、歷史與文化查核。', type: "text", dependsOn: ["theme"] },
    { id: 2, name: '長影音腳本撰寫', icon: 'FileText', category: 'Content', desc: '根據美食背景資料產出5-10分鐘YouTube影片腳本。', type: "text", dependsOn: ["theme", "step1"] },
    { id: 3, name: '長影音 SEO 優化', icon: 'Search', category: 'Optimization', desc: '生成SEO標題、Hashtags、說明欄。', type: "text", dependsOn: ["theme", "step2"] },
    { id: 4, name: '短影音腳本', icon: 'Video', category: 'Content', desc: '生成60秒內爆款短影音腳本。', type: "text", dependsOn: ["theme", "step1"] },
    { id: 5, name: '短影音SEO', icon: 'Search', category: 'Optimization', desc: '生成短影音SEO標題。', type: "text", dependsOn: ["theme", "step4"] },
    { id: 6, name: '長影音縮圖設計', icon: 'ImageIcon', category: 'Visuals', desc: '生成16:9 YouTube縮圖。', type: "code", language: "markdown", dependsOn: ["theme", "step3"], aspectRatio: "16:9" },
    { id: 7, name: '短影音封面設計', icon: 'ImageIcon', category: 'Visuals', desc: '生成9:16 Shorts封面。', type: "code", language: "markdown", dependsOn: ["theme", "step5"], aspectRatio: "9:16" },
    { id: 8, name: '品牌級美食海報', icon: 'ImageIcon', category: 'Visuals', desc: '生成高質感餐飲行銷海報。', type: "code", language: "markdown", dependsOn: ["theme"], aspectRatio: "9:16" },
    { id: 9, name: 'Suno AI 美食配樂', icon: 'Music', category: 'Audio', desc: '生成三組美食影片音樂。', type: "code", language: "markdown", dependsOn: ["theme", "step1"] },
    { id: 10, name: '社群美食發布中心', icon: 'Facebook', category: 'Distribution', desc: '生成Instagram、Facebook、小紅書貼文。', type: "social", language: "markdown", dependsOn: ["theme", "step1"] }
  ],
  travelpreneur: [
    { id: 1, name: '旅遊目的地背景查核', icon: 'Database', category: 'Research', desc: '蒐集目的地歷史、文化、景點、美食、交通與旅遊資訊，建立可信基礎資料。', type: "text", dependsOn: ["theme"] },
    { id: 2, name: '長影音腳本', icon: 'FileText', category: 'Content', desc: '產出8~12分鐘YouTube旅遊攻略影片。', type: "text", dependsOn: ["theme", "step1"] },
    { id: 3, name: '長影音SEO', icon: 'Search', category: 'Optimization', desc: '產生YouTube SEO內容。', type: "text", dependsOn: ["theme", "step2"] },
    { id: 4, name: 'Shorts腳本', icon: 'Video', category: 'Content', desc: '生成60秒旅遊Shorts腳本。', type: "text", dependsOn: ["theme", "step1"] },
    { id: 5, name: 'Shorts SEO', icon: 'Search', category: 'Optimization', desc: '生成Shorts SEO。', type: "text", dependsOn: ["theme", "step4"] },
    { id: 6, name: 'YouTube縮圖', icon: 'ImageIcon', category: 'Visuals', desc: '生成16:9縮圖Prompt。', type: "code", language: "markdown", dependsOn: ["theme", "step3"], aspectRatio: "16:9" },
    { id: 7, name: 'Shorts封面', icon: 'ImageIcon', category: 'Visuals', desc: '生成9:16 Shorts封面。', type: "code", language: "markdown", dependsOn: ["theme", "step5"], aspectRatio: "9:16" },
    { id: 8, name: '旅遊品牌海報', icon: 'ImageIcon', category: 'Visuals', desc: '生成高質感旅遊宣傳海報。', type: "code", language: "markdown", dependsOn: ["theme"], aspectRatio: "9:16" },
    { id: 9, name: 'Suno AI 配樂', icon: 'Music', category: 'Audio', desc: '生成旅遊影片背景音樂。', type: "code", language: "markdown", dependsOn: ["theme", "step1"] },
    { id: 10, name: '社群發布中心', icon: 'Facebook', category: 'Distribution', desc: '生成IG、Facebook、Threads、小紅書旅遊貼文。', type: "social", language: "markdown", dependsOn: ["theme", "step1"] }
  ],
  pet: [
    { id: 1, name: '寵物問題研究與專家查核', icon: 'Database', category: 'Research', desc: '深入分析寵物問題成因、行為學、獸醫觀點與最新研究，建立可信基礎資料。', type: "text", dependsOn: ["theme"] },
    { id: 2, name: '長影音腳本', icon: 'FileText', category: 'Content', desc: '產出8~12分鐘問題解決型YouTube影片。', type: "text", dependsOn: ["theme", "step1"] },
    { id: 3, name: '影片SEO優化', icon: 'Search', category: 'Optimization', desc: '產生YouTube SEO。', type: "text", dependsOn: ["theme", "step2"] },
    { id: 4, name: 'Shorts腳本', icon: 'Video', category: 'Content', desc: '生成60秒爆款短影音。', type: "text", dependsOn: ["theme", "step1"] },
    { id: 5, name: 'Shorts SEO', icon: 'Search', category: 'Optimization', desc: '生成Shorts SEO。', type: "text", dependsOn: ["theme", "step4"] },
    { id: 6, name: 'YouTube縮圖', icon: 'ImageIcon', category: 'Visuals', desc: '生成三組高CTR縮圖。', type: "code", language: "markdown", dependsOn: ["theme", "step3"], aspectRatio: "16:9" },
    { id: 7, name: 'Shorts封面', icon: 'ImageIcon', category: 'Visuals', desc: '生成9:16封面。', type: "code", language: "markdown", dependsOn: ["theme", "step5"], aspectRatio: "9:16" },
    { id: 8, name: '用品推薦與品牌合作', icon: 'FileText', category: 'Content', desc: '推薦相關用品、品牌合作與導購文案。', type: "text", dependsOn: ["theme", "step1"] },
    { id: 9, name: 'Suno AI配樂', icon: 'Music', category: 'Audio', desc: '生成三組寵物影片背景音樂。', type: "code", language: "markdown", dependsOn: ["theme"] },
    { id: 10, name: '社群內容中心', icon: 'Facebook', category: 'Distribution', desc: '生成IG、FB、Threads、小紅書完整貼文。', type: "social", language: "markdown", dependsOn: ["theme", "step1"] }
  ]
};
